---

- name: Install ds packages if they are missing.
  ansible.builtin.include_role:
      name: install_dspkg
  vars:
      state: present

# Now let call the plugin
- name: debug dsserver_instances
  debug:
    var: dsserver_instances

- ds.ansible_ds.ds_server:
   content:
      # At the global level state is always present
      # to avoid removing ALL instances
      state: "present"
      prefix:  "{{dsserver_prefix}}"
      instances: "{{dsserver_instances}}"
  tags: vars
