---
- name: Playbook to backup DS instance to controller
  hosts: localhost
  become: true

  vars:
    dsbackup_to_controller: yes
    # dsbackup_keep_on_server: yes

  roles:
  - role: dsbackup
    state: present
