---
- name: Playbook to copy a backup from controller to the server
  hosts: localhost
  become: true

  vars:
    dsbackup_name: localhost.localdomain_localhost_2022_05_19_21_25_05
    dsbackup_from_controller: yes

  roles:
  - role: dsbackup
    state: copied
