---
- name: Playbook to restore DS instance from controller
  hosts: localhost
  become: true

  vars:
    dsbackup_name: localhost.localdomain_localhost_2022_05_19_21_25_05
    dsbackup_from_controller: yes

  roles:
  - role: dsbackup
    state: restored
