---
- name: Get DS backup dir
  import_tasks: "{{ role_path }}/tasks/get_dsbackup_dir.yml"

- name: Stat backup on server
  stat:
    path: "{{ dsbackup_dir }}/{{ dsbackup_item }}"
  register: result_backup_stat

- name: Fail on missing backup directory
  fail: msg="Unable to find backup {{ dsbackup_item }}"
  when: result_backup_stat.stat.isdir is not defined

- name: Stop DS instance, if started
  service:
    name: dirsrv@localhost
    state: stopped

- name: Restore backup
  command:
    argv:
      - dsctl
      - localhost
      - bak2db
      - "{{ dsbackup_item }}"
  register: result_dsrestore
  ignore_errors: yes

- name: Report error for restore operation
  debug:
    msg: "{{ result_dsrestore.stderr }}"
  when: result_dsrestore is failed
  failed_when: yes
