---

  - name: Collect DS Instances
    ds.ansible_ds.ds_info:
        prefix: "{{ lookup('env', 'PREFIX') | default('', True) }}"
    register: result
  - name: "Set variables"
    set_fact:
      dsserver_instances: "{{ result.my_useful_info.dsserver_instances }}"

  - name: Debug
    ansible.builtin.debug:
      msg:
        - Result is {{ dsserver_instances }}
