---
- name: Fail on invalid ds389_backup_archive_path
  ansible.builtin.fail:
    msg: "ds389_backup_archive_path {{ ds389_backup_archive_path }} is not valid"
  when: ds389_backup_archive_path is not defined or
        ds389_backup_archive_path | length < 1

- name: Set controller source directory
  ansible.builtin.set_fact:
    ds389_backup_controller_dir:
      "{{ ds389_backup_controller_path | default(lookup('env', 'PWD')) }}"

- name: Set ds389_backup_item
  ansible.builtin.set_fact:
    ds389_backup_item: "{{ ds389_backup_archive_path }}"

- name: Stat backup to copy
  ansible.builtin.stat:
    path: "{{ ds389_backup_controller_dir }}/{{ ds389_backup_archive_path }}"
  register: ds389_backup_stat_result
  delegate_to: localhost
  become: false

- name: Fail on missing backup to copy
  ansible.builtin.fail:
    msg: "Unable to find backup {{ ds389_backup_archive_path }}"
  when: ds389_backup_stat_result.stat.isdir is not defined

- name: Get DS backup dir
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/get_ds389_backup_dir.yml"

- name: Copy backup files to server for "{{ ds389_backup_item }}"
  ansible.builtin.copy:
    src: "{{ ds389_backup_controller_dir }}/{{ ds389_backup_archive_path }}/"
    dest: "{{ ds389_backup_dir }}/{{ ds389_backup_item }}"
    owner: dirsrv
    group: dirsrv
    mode: u=rw,go=r
    directory_mode: u=rwx,go=
