---
- name: Get DS bak dir from lib389
  ansible.builtin.command: "{{ ansible_python_interpreter | default('/usr/bin/python') }}"
  args:
    stdin: |
      from lib389.paths import Paths
      print(Paths("localhost").backup_dir)
  register: ds389_backup_dir_result
  changed_when: false

- name: Set DS backup dir
  ansible.builtin.set_fact:
    ds389_backup_dir: "{{ ds389_backup_dir_result.stdout_lines | first }}"
