---
- name: Get DS bak dir from lib389
  ansible.builtin.command: "{{ ansible_python_interpreter | default('/usr/bin/python') }}"
  args:
    stdin: |
      from lib389.paths import Paths
      print(Paths("localhost").backup_dir)
  register: result_lib389_backup_dir
  changed_when: false

- name: Set DS backup dir
  ansible.builtin.set_fact:
    ds389_backup_dir: "{{ result_lib389_backup_dir.stdout_lines | first }}"
