---
- name: Get DS backup dir
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/get_ds389_backup_dir.yml"

- name: Stat backup on server
  ansible.builtin.stat:
    path: "{{ ds389_backup_dir }}/{{ ds389_backup_item }}"
  register: ds389_backup_stat_result

- name: Fail on missing backup directory
  ansible.builtin.fail:
    msg: "Unable to find backup {{ ds389_backup_item }}"
  when: ds389_backup_stat_result.stat.isdir is not defined

- name: Stop DS instance, if started
  ansible.builtin.service:
    name: dirsrv@localhost
    state: stopped

- name: Restore backup
  ansible.builtin.command:
    argv:
      - dsctl
      - localhost
      - bak2db
      - "{{ ds389_backup_item }}"
  register: ds389_backup_dsrestore_result
  ignore_errors: true

- name: Report error for restore operation
  ansible.builtin.debug:
    msg: "{{ ds389_backup_dsrestore_result.stderr }}"
  when: ds389_backup_dsrestore_result is failed
  failed_when: true
