---
- name: Playbook to backup DS instance to controller
  hosts: localhost
  become: true

  vars:
    ds389_backup_to_controller: true
    # ds389_backup_keep_on_server: true

  roles:
    - role: ds389_backup
      state: present
