---
- name: Playbook to copy backup from server
  hosts: localhost
  become: true

  vars:
    ds389_backup_name: localhost_2022_05_19_21_25_05
    ds389_backup_to_controller: true

  roles:
    - role: ds389_backup
      state: copied
