---
- name: Playbook to copy all backups from server
  hosts: localhost
  become: true

  vars:
    ds389_backup_name: all
    ds389_backup_to_controller: true

  roles:
    - role: ds389_backup
      state: copied
