---
- name: Playbook to remove all DS instances
  hosts: ldapservers
  become: true

  tasks:
    - name: "Remove all 389ds instances on targeted hosts"
      ds389.ansible_ds.ds389_server:
        state: absent
