---
- name: Playbook to create a set of DS instances
  hosts: ldapservers
  become: true

  tasks:
    - name: "Create 389ds instances according to the inventory"
      ds389.ansible_ds.ds389_server:
