---
- name: Playbook to restore DS instance from controller
  hosts: localhost
  become: true

  vars:
    ds389_backup_name: localhost.localdomain_localhost_2022_05_19_21_25_05
    ds389_backup_from_controller: true

  roles:
    - role: ds389_backup
      state: restored
