---

- name: Install ds packages if they are missing.
  ansible.builtin.include_role:
      name: install_dspkg
  vars:
      state: present

# Now let call the plugin
- name: debugds389_server_instances
  debug:
    var: ds389_server_instances

- ds389.ansible_ds.ds389_server:
   content:
      # At the global level state is always present
      # to avoid removing ALL instances
      state: "present"
      prefix:  "{{ds389_server_prefix}}"
      instances: "{{ds389_server_instances}}"
  tags: vars
