---
namespace: ds389
name: ansible_ds
version: 1.0.0
description: A set to install and deploy 389 Directory Server

authors:
  - Pierre Rogier <progier@redhat.com>
  - Simon Pichugin <spichugi@redhat.com>

repository: https://github.com/ds389/ansible-ds
documentation: https://github.com/ds389/ansible-ds/blob/main/README.md
homepage: https://github.com/ds389/ansible-ds
issues: https://github.com/ds389/ansible-ds/issues

readme: README.md
license:
  - GPL-3.0-or-later

tags:
  - "linux"
  - "ds389"
  - "ds"
  - "ldap"
  - "collection"

build_ignore:
  - 'tests*'
  - '*.tmpl'
