name: Python lint
on: [push, pull_request]

jobs:
  python_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add GITHUB_WORKSPACE as a safe directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Build ds389_ansible collection.
      uses: ./.github/actions/build

    - name: Run lint (python)
      run: make github_pylint
